version: '3'
services:
  app:
    image: noteisenheim/lab4-ds:v2
    volumes:
      - ./www/:/app/www/
      - ./www/media:/app/www/media
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www/media:/www/media
    depends_on:
      - app
    ports:
      - "80:80"